services:
  express:
    build:
      context: ./
    volumes:
      - ./src:/app/src
      # - /mnt/video-volume/lost+found:/app/src/media
    deploy:
      resources:
        reservations:
          memory: 5G
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - 6379:6379    
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    deploy:
      resources:
        reservations:
          memory: 1G
    command: redis-server /usr/local/etc/redis/redis.conf

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      # - /mnt/video-volume/lost+found:/usr/share/nginx/html/media
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - express
  
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  uploader:
    build:
      context: ./uploader
    env_file:
      - .env
    # volumes:
      # - /mnt/video-volume/lost+found:/app/tmp

  cache:
    image: memcached
    command:
      - --conn-limit=1024
      - --memory-limit=4096
      - --threads=4
    ports:
      - 11211:11211
volumes:
  nginx_secrets: