services:
  express:
    build:
      context: ./
    volumes:
      - ./src:/app/src
      - /mnt/video-volume/lost+found:/app/src/media
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - 6379:6379    
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    deploy:
      resources:
        reservations:
          memory: 1G
    command: redis-server /usr/local/etc/redis/redis.conf

  nginx:
    image: jonasal/nginx-certbot
    environment:
      - CERTBOT_EMAIL=jiechenmc@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - /mnt/video-volume/lost+found:/usr/share/nginx/html/media
      - ./nginx:/etc/nginx/user_conf.d
      - nginx_secrets:/etc/letsencrypt
    depends_on:
      - express
    
  uploader:
    build:
      context: ./uploader
    env_file:
      - .env
    volumes:
      - /mnt/video-volume/lost+found:/app/tmp

volumes:
  nginx_secrets: