services:
  express:
    build:
      context: ./
    volumes:
      - ./src:/app/src
      - /mnt/video-volume/lost+found:/app/src/media
    env_file:
      - .env

  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy/worker.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 80:80
