global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "mdb-exporter"
    static_configs:
      - targets: ["mdb_exporter:9216"]
  
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "haproxy"
    static_configs:
      - targets: ["haproxy:8405"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx_exporter:9113"]