# free-form (string) arguments, some arguments on separate lines with the 'args' keyword
# 'args' is a task keyword, passed at the same level as the module
- name: Compose Down
  ansible.builtin.command: docker compose -f {{project_dir}}/docker-compose.worker.yml down
- name: Compose Express
  ansible.builtin.command: docker compose -f {{project_dir}}/docker-compose.worker.yml up --scale express=2 -d
