---
- name: root
  hosts: all
  become: true
  become_method: sudo
  remote_user: ubuntu
  vars_files:
    - vars/default.yml

  tasks:
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/clone.yml
    - import_tasks: tasks/redis.yml
      when: "'redis' in group_names"
    - import_tasks: tasks/worker.yml
      when: "'worker' in group_names"
    - import_tasks: tasks/express.yml
      when: "'express' in group_names"